'use strict';

module.exports = {
  ARCHIVE_MARKER: 'ARCHIVE_ORIGIN=',
  TUTOR_TICKET_MARKER: 'TUTOR_TICKET=',
  QUIZ_ANSWER_PREFIX: 'quiz_answer:',
  RAG_DL_PREFIX: 'rag_dl:',
  MAX_CALENDAR_SIZE_BYTES: 2 * 1024 * 1024,
  MAX_REDIRECTS: 3,
  DEFAULT_CALENDAR_EVENT_LIMIT: 5
};
